### ISSUE TITLE
'Next Prayer' Time is Delayed by One Prayer

### ISSUE THREAD

**Issue by muhzakari** [Do-Repo/PrayerApp#1]
Hi, nice app. Just a little error with regards the 'next prayer' on the homepage header, it is delayed by a prayer time. For example instead of displaying Asr, it displays Zuhr.

![Screenshot_20220415-130505_1](https://user-images.githubusercontent.com/41239409/163569248-dfa0f986-ba7d-4440-8fe0-627c63ebde44.jpg)

**Comment by Do-Repo** [comment]
Hi Muhammed,
Are you sure that the time on your device is right?

**Comment by muhzakari** [comment]
Yes, of course.. there are other similar apps and they're working fine. The way, it works is that when the current prayer time is Zuhr, the next prayer will be highlighted & start counting down to that prayer,  instead of the current prayer time as is shown in the app.

**Comment by Do-Repo** [comment]
I don't understand what you mean, because I've tried on 3 different devices and it works like expected. Can you show me a screenshot of the full screen with the device time please

**Comment by muhzakari** [comment]
The countdown is towards the next prayer, so it should be the one to be indicated and not the current prayer. 
![iMarkup_20220416_063733](https://user-images.githubusercontent.com/41239409/163663240-7fc3e37b-115e-4a44-9665-e58dd91df19d.jpg)


Also, attached is a screenshot of the Muslim pro app, where the countdown is for the next prayer rather than the current prayer.

![Uploading Screenshot_20220416-063859.jpg…]()

**Comment by muhzakari** [comment]
![Screenshot_20220416-063859](https://user-images.githubusercontent.com/41239409/163663386-e22b7721-2a9d-45b1-8061-7bfd51097fe9.jpg)

Screenshot from the Muslim pro App

**Comment by Do-Repo** [comment]
That's not my app?

**Comment by muhzakari** [comment]
Sorry bro, maybe cos I just woke up..

As mentioned earlier, the next prayer is dhuhr, whose countdown is intended i.e in 5hrs time. Therefore the prayer to be counted down to should be the next prayer.
![iMarkup_20220416_070054](https://user-images.githubusercontent.com/41239409/163663885-7b02b144-4804-4fae-8cca-744c4ee3b394.jpg)


Just as shown in the Muslim pro app 
![Screenshot_20220416-063859](https://user-images.githubusercontent.com/41239409/163663902-1d5e30e7-7d7d-4ef6-9d79-bf6b9f4a3234.jpg)

**Comment by muhzakari** [comment]
Sorry again bro, since the next prayer on your prayer timetable is Shuruq, that should be the next prayer unlike Muslim pro, that has no Shuruq in its Time table.

Hope, you understand.

**Comment by Do-Repo** [comment]
Yes, I understand you now, and it's working as intended.
The app shows you which prayer is still valid to be prayed. In this case you can still pray Subh before Dhuhr.
And you have still 5 hours left to pray Subh before Dhuhr comes in.

It shows current prayer and how much time left for next prayer to begin. The only problem I see here now is to change Fajr to Subh after Shuruq
